### PR TITLE
CompileSdkVersion version changed to 28.

### PR DESCRIPTION
**Pull request by ashot-israelyan**
The problem occurs in the React Native projects which have compileSdkVersion higher than 26. 

Here is the link of that issue.

https://github.com/bolan9999/react-native-spring-scrollview/issues/26

### CODE REVIEW

**Comment by ATShiTou** [comment]
@Whallas @ashot-israelyan  Have you tried it on main project with API 26 or other SDK version? The  [react-native-largelist demo project](https://github.com/bolan9999/react-native-largelist) depends on this library and the main project's compileSdkVersion is also 28. But it works well.

I am not good at gradle configuration. I do not understand why this error occurs. I have tried to check out other react-native libraries such as `react-native-gesture-handler`, `react-native-blur`. They all use `safeExtGet` method.  I can not reproduce this issue, so can you test it for me with `safeExtGet` like this:
```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android{
    compileSdkVersion safeExtGet('compileSdkVersion', 26)
    buildToolsVersion safeExtGet('buildToolsVersion', '26.0.3')
}
```

or

```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android{
    compileSdkVersion safeExtGet('compileSdkVersion', 28)
    buildToolsVersion safeExtGet('buildToolsVersion', '28.0.3')
}
```

**Comment by ATShiTou** [comment]
I think maybe the special version 28 is not good too. Maybe other issue occurs with this change. Waiting for your response. Thank you!

**Comment by ashot-israelyan** [comment]
@ATShiTou I tried to do as you said, but it didn't solve my issue. Actually I am using your largelist library and the spring-scrollview is just a dependency. But changing the spring-scrollview compileSdkVersion didn't break the largelist library.

**Comment by ATShiTou** [comment]
If your main project's supportLibVersion is lower than `28.0.0` , this special version 28 will cause this issue:
```
ERROR: Unable to resolve dependency for ':lottie-react-native@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:27.1.1.
```

**Comment by ashot-israelyan** [comment]
No my projects supportLibVersion is exactly `28.0.0`. When I changed the `compileSdkVersion` to `26` I got same error as described in this [issue](https://github.com/bolan9999/react-native-spring-scrollview/issues/26). The same for `safeExtGet`. The only fix that helps is changing your library's `compileSdkVersion` to `28`.

If you could update the `complieSdkVersion` I would be very grateful. I think after some time more people will get such kind of errors.

The library is really awesome and it fully fixes the problem that can't be fixed with `ScrollView` or `FlatList`.

**Comment by ATShiTou** [comment]
The `safeExtGet ` works only when your main project's root build.gradle has this content:
```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 20
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
...
}
```
And quote it in your app build.gradle :
```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
}
```

If your main project does not have those configuration, `safeExtGet` will use the default compileSdkVersion 28.

Another question: which build.gradle do you change to test ? Your main project /app/build.gradle or the build.gradle of the react-native-spring-scrollview?

**Comment by ashot-israelyan** [comment]
I have changed `node_modules/react-native-spring-scrollview/android/build.gradle` compileSdkVersion to `28`.

**Comment by ATShiTou** [comment]
Any issue when you change to `compileSdkVersion safeExtGet('compileSdkVersion', 28)`

**Comment by ashot-israelyan** [comment]
In my project, when I do like you set I get [this](https://github.com/bolan9999/react-native-spring-scrollview/issues/26) errors.

**Comment by ATShiTou** [comment]
Sorry, I do not believe. `compileSdkVersion safeExtGet('compileSdkVersion', 28)` and `compileSdkVersion 28` are the same work. And `compileSdkVersion safeExtGet('compileSdkVersion', 28)` is more safe.

**Pull request closed without merging**
