### PR TITLE
Update path of TextInputState

### PR DESCRIPTION
**Pull request by rafaelmotta**
This pull request updates the path of TextInputState imports, changed in version 0.61.

This is a breaking change!

### CODE REVIEW

**Comment by ATShiTou** [comment]
Thank you for your PR.

It destroyed compatibility.  maybe I should try to find another way to fix it.

**Comment by gitstud** [comment]
Should have checked open PR's before making mine, but happy to see this!

**Comment by ATShiTou** [comment]
fixed

**Comment by zuijiusi** [comment]
> 
> 
> fixed

same question in RN 0.61.2,and fixed failed.

**Comment by fanwenfu** [comment]
same question in RN 0.61.4,and fixed failed.
image

**Comment by anka-213** [comment]
@ATShiTou Will you make a release with this fix soon or is there anything that makes it complicated?

**Pull request closed without merging**
